"""
Copyright (c) 2024 Ilias Karimalis. All rights reserved.

gosdt: Implementation of General Optimal Sparse Decision Tree
"""


from __future__ import annotations

# This file is generated by scikit-build-core
from ._version import version as __version__

from ._binarizer import NumericBinarizer
from ._threshold_guessing import ThresholdGuessBinarizer
from .MSPLIT import MSPLIT

__all__ = [
    "__version__",
    "NumericBinarizer",
    "ThresholdGuessBinarizer",
    "MSPLIT",
]

# Default placeholders when the compiled extension is not available.
GOSDTClassifier = None
Status = None
SPLIT = None
LicketySPLIT = None

# GOSDT-backed classes require the compiled extension. Keep imports lazy-safe so
# MSPLIT can be used even when native dependencies are not installed.
try:
    from ._classifier import GOSDTClassifier
    from ._libgosdt import Status
    from .SPLIT import SPLIT
    from .LicketySPLIT import LicketySPLIT

    __all__.extend(["GOSDTClassifier", "Status", "SPLIT", "LicketySPLIT"])
except ModuleNotFoundError as exc:
    if exc.name not in {"split._libgosdt", "split._classifier"}:
        raise
